### ISSUE TITLE
Crashes with Fancy Menu

### ISSUE THREAD

**Issue by Rafii2198** [aratakileo/emogg#8] opened 2023-07-25 23:44 UTC
Fancy Menu is a mod that lets you customize nearly every GUI and even add custom ones. I found that when you enter such Custom GUI with Emogg installed, the game instantly crashes.

I already contacted the author of Fancy Menu, and he said that the issue lies on the Emogg side. Here is his message
> Okay, so the game throws a NullPointer related to the Emoji mod, but it crashes when I literally just render the menu title using vanilla methods, so I don't think I do anything there that should cause this on FM's end (could be wrong of course).

And also provided a link to the line where it crashes https://github.com/Keksuccino/FancyMenu/blob/17242a506a581a403eaac14934b3da020a12d48c/src/main/java/de/keksuccino/fancymenu/menu/fancy/guicreator/CustomGuiBase.java#L51
 And this is the important part of the log (attached at the bottom)
 ```
 at pextystudios.emogg.emoji.EmojiFontRenderer.method_1727(EmojiFontRenderer.java:157) ~[emogg-1.0-BETA.4-1.19.4.jar:?]
    at net.minecraft.class_332.method_25300(class_332.java:148) ~[client-intermediary.jar:?]
    at de.keksuccino.fancymenu.menu.fancy.guicreator.CustomGuiBase.method_25394(CustomGuiBase.java:51) ~[fancymenu_fabric_2.14.9_MC_1.19.4.jar:?]
 ```

If you can check what is going on, I would be really grateful and will also tell the FM's author. 

[Here](https://gist.github.com/Keksuccino/bf47ef702034b67679968a92371ebe7f) is the full log of the game crashing with only FM and Emogg + dependencies

**Comment by aratakileo** [comment] 2023-07-26 00:03
Thank you so much for reporting this mods conflict! I will come back to you soon with an answer regarding the resolution of this conflict!

I also want to inform you that the development of the closest versions of the mod will be aimed at the Minecraft version 1.20.x! In this connection, I would like to know if this fix is important to you for Minecraft version 1.19.4, because you have a certain build of mods for this version or the server? Or will it be enough for you to have the fix implemented for Minecraft version 1.20.x?

**Comment by Rafii2198** [comment] 2023-07-26 00:16
This is mainly for a modpack around one mod that it still on 1.19.4, that mod aims to enhance experience on RPG server, Wynncraft and there were plans to update it to 1.20 but then Wynncraft dropped an update, a massive one, and it seems that mod is not going to be ported until everything from the update will be properly adapted, how much time it will take is not something I know, I am not a dev, only a Moderator their discord server and merely a contributor for the mod.

So like, the modpack can obviously live without this mod until it gets ported to 1.20. I currently have another mod that adds emojis, but ngl that one is pretty limited (no custom emojis) and causes troubles with some stuff with mods and even on that server after it got an update, so I was looking for a replacement and found this amazing mod, and so I wanted to put it in, but one of the key points of the modpack is that it has some exclusive features and Emogg makes it impossible to enter these features, so naturally I can't include this for the time being

All in all, if you could make a fix for 1.19.4, then that would be great for me, but you shouldn't have to go out of your way to implement it in the older version just for the sake of my modpack. I will be happy if it gets fixed at all, especially when I have no idea when the update to 1.20 will come in

**Comment by aratakileo** [comment] 2023-07-26 00:41
Thank you for answering my questions in such detail! You may be aware that maintaining and implementing a support mechanism for older versions takes quite a lot of resources that can be used to implement a new functionality or to fix critical problems. Because of this, I seriously thought that I should somehow optimize this process and abandon support for some versions, maybe for a while, or maybe for completely. Based on the statistics of downloading various versions, the most popular version of the Minecraft mod version 1.20.x turned out to be, the popularity of which was 6 or even 10 times higher compared to other versions. In this connection, I decided to abandon support for other versions with the exception of 1.20.x. However, your appeal reminded me of what I myself encountered, that there are many cool mods that, like the Effective mod, which does not support versions of minecraft newer than 1.19.2, do not support newer versions of Minecraft, basically 1.20.x. According to my observations, the difference between version 1.19.4 and 1.20.x is not that big (at least in the segment of the code in which the mod interacts), therefore, I am thinking about transferring changes in the code, later, from version 1.20.x on version 1.19.4 😄

**Comment by aratakileo** [comment] 2023-07-26 12:32
Unfortunately, I can't reproduce the crash you described on Minecraft version 1.19.4 with the version of emogg that you had. Thanks to the information you provided, I approximately understood what the problem was, despite the fact that it has more to do with FancyMenu than with emogg, I still implemented a possible solution to it. You can try it out on Minecraft version 1.20 or 1.20.1!
[[Download build for 1.20.x. Don't forget to unzip!]](https://github.com/aratakileo/emogg/files/12172389/emogg-1.0-BETA.5-1.20.x.zip)

**Closed by aratakileo** 2023-07-26 12:32 UTC
Labels: conflict

**Comment by Rafii2198** [comment] 2023-07-26 12:41
I loaded my configuration in 1.20 and the version you provided has fixed the issue, everything works with it. I also tested the version from Modrinth, just to make sure if it's not a 1.19.4 specific bug but that one crashed too which means the fix you implemented now solved the issue! Thank you :)

**Comment by aratakileo** [comment] 2023-07-26 12:56
You're welcome! I am glad to hear that the problem has been solved ╰(*°▽°*)╯
