### ISSUE TITLE
It does not load on macOS due to the gif image processing system

### ISSUE THREAD

**Issue by LemmaEOF** [aratakileo/emogg#13] opened 2023-08-02 07:18 UTC
[Emogg uses Java's Abstract Web Toolkit's `BufferedImage` for gif splitting](https://github.com/aratakileo/emogg/blob/main/src/main/java/pextystudios/emogg/util/EmojiUtil.java#L49), which fails in an `-XstartOnFirstThread` environment like MacOS. It just ends up freezing the game as soon as any gif is passed through the `splitGif` method. It might be possible to use Minecraft's `NativeImage` for this purpose instead, but I'm not sure.

**Comment by aratakileo** [comment] 2023-08-02 15:38
Hey! As a result, does the game load or not?

**Comment by aratakileo** [comment] 2023-08-02 19:11
Oh, I'm so sorry about that. I already have an idea of a possible solution to the problem. I will come back with a new answer when a possible solution is ready! 👋

**Comment by aratakileo** [comment] 2023-08-02 19:27
If you provide me with your logs, it will be easier for me to find a solution to the problem. Thank you in advance!

**Comment by aratakileo** [comment] 2023-08-02 20:07
I'm here with a possible solution to your problem! According to measurements on my device, the emoji loading speed for the mod has increased by 6.7 times. Don't forget to unzip: [[Download possible solution version of mod]](https://github.com/aratakileo/emogg/files/12244203/emogg-1.0-BETA.7-1.20.x.zip)

**Comment by LemmaEOF** [comment] 2023-08-04 02:11
Ooh, I'll give this a try! I could provide a log, but sadly it wouldn't actually help much - a toolbox freeze will always just stop the game in its tracks without any log message.

**Comment by LemmaEOF** [comment] 2023-08-04 02:17
No luck with the new beta, sadly - it still freezes in the exact same place while loading.

**Comment by aratakileo** [comment] 2023-08-04 09:10
Oh no! Do you have the Optifine mod installed? Emogg is not compatible with Optifine.

You can easily provide me with logs, even if all interfaces are freezed and crashed in the end. To do this, it's enough to provide me with a file whose name indicates the closing date of the game launched with this mod. Look at the file creation time. Select the file whose time approximately coincides with the closing time of the game with this mod. If you can't find the file or you don't remember when you finished the game with this mod. Run it again, wait until the game closes completely and only then look for the file. The file itself will be located in the logs folder, which is located in the same folder as the mods folder.

**Comment by LemmaEOF** [comment] 2023-08-04 23:39
Nah I don’t use OptiFine lol, I’m a mod dev myself so I know how much it breaks things. I’ll see if I can get a log later, but I scoured through them and nothing notable came up.

**Comment by sisby-folk** [comment] 2023-08-05 02:18
To be very explicit about our understanding of the issue here, if you want mac compatibility, you need to find a way to remove [this line](https://github.com/aratakileo/emogg/blob/main/src/main/java/pextystudios/emogg/util/EmojiUtil.java#L23) (i.e, avoid using `awt` at all, have zero lines that start with `import java.awt`), after which the mod should work on mac.

We've seen other mods be mac-incompatible due to using `awt` e.g. Antique Atlas, and we had to remove awt ourselves for it to run correctly.

**Comment by aratakileo** [comment] 2023-08-05 09:39
Unfortunately, it will not be possible to replace it this way, because NativeImage does not work with metadata

**Comment by aratakileo** [comment] 2023-08-05 09:54
This will return BufferedImage anyway:
https://github.com/aratakileo/emogg/blob/main/src/main/java/pextystudios/emogg/util/EmojiUtil.java#L65

**Comment by aratakileo** [comment] 2023-08-05 09:55
@Abbie5 do yoy have any idea how we can fix it?

**Comment by Abbie5** [comment] 2023-08-05 10:52
i'm a bit busy atm but i'll see what i can do

**Comment by aratakileo** [comment] 2023-08-05 11:04
Thank you

**Comment by Abbie5** [comment] 2023-08-07 10:25
weird, i can't reproduce this issue on my (apple silicon) mac - is the issue exclusive to intel macs?

**Comment by aratakileo** [comment] 2023-08-07 10:32
@Abbie5 thank you for your help!

**Comment by aratakileo** [comment] 2023-08-07 10:34
@LemmaEOF unfortunately, due to a lack of information about the problem (at least logs) I am forced to mark this issue as invalid and close it ;(

**Comment by aratakileo** [comment] 2023-08-07 11:14
I did this because of a lack of information about the problem, not because you somehow showed that the problem does not exist. According to information from the forums, the problem with BufferedImage was solved in the Minecraft version for macOS. It would really be easier to understand exactly what the problem is if logs and information about the device were provided

**Comment by artemisSystem** [comment] 2023-08-07 11:24
I'm having this issue on my 14" M1 Max Macbook Pro, 32GB ram, running Ventura 13.4.1

what's your machine, @Abbie5?

**Comment by aratakileo** [comment] 2023-08-07 11:33
Now we have confirmed for sure that the problem has not been fixed in the new versions of Minecraft

**Comment by Abbie5** [comment] 2023-08-07 12:02
> what's your machine, @Abbie5?

2020 M1 MacBook Air w/ 8GB RAM running Ventura 13.4.1

**Comment by aratakileo** [comment] 2023-08-07 13:32
@LemmaEOF @artemisSystem Does this build fix the issue?
[emogg-1.0-BETA.7-1.20.x.zip](https://github.com/aratakileo/emogg/files/12280307/emogg-1.0-BETA.7-1.20.x.zip)
@Abbie5 Does this build work for you?

**Comment by aratakileo** [comment] 2023-08-07 15:45
I've looked at many implementations of gif reading, they all use BufferedImage. Unfortunately, I have no more ideas how to fix it

**Comment by Abbie5** [comment] 2023-08-07 16:05
LWJGL STBImage has some methods for reading GIFs, have you had a look at that?

(btw, NativeImage uses STBImage internally, it just doesn't expose any of the GIF stuff)

**Comment by aratakileo** [comment] 2023-08-07 21:54
@Abbie5 I tried to realize this:
https://github.com/aratakileo/emogg/blob/native-gif-image-realisation/src/main/java/pextystudios/emogg/NativeGifImage.java

this led to the fact that after several uses of the implementation, the game simply collapses due to a critical error outside the virtual machine, on the side of this library:
https://mclo.gs/WZ4k5Gs

In addition, for some reason it is not possible to read gif files.

**Comment by aratakileo** [comment] 2023-08-10 13:50
The game collapsed because the library refused to read one of the GIF images. I deleted this emoji.

@Abbie5 @LemmaEOF @artemisSystem try this build. Now it have to work correctly for MacOS (don't forget to unzip!):
[emogg-1.0-BETA.8-1.20.x.zip](https://github.com/aratakileo/emogg/files/12313455/emogg-1.0-BETA.8-1.20.x.zip)

**Closed by aratakileo** 2023-08-10 13:50 UTC
Labels: freeze
